% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Apr-2018 19:27:46
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('pH_salt.mat');

ALaCl3 = saveVarsMat.ALaCl3; % <1x1 containers.Map> unsupported class

BKCl = saveVarsMat.BKCl; % <1x1 containers.Map> unsupported class

CeCl3 = saveVarsMat.CeCl3; % <1x1 containers.Map> unsupported class

HfCl4 = saveVarsMat.HfCl4; % <1x1 containers.Map> unsupported class

K3PO4 = saveVarsMat.K3PO4; % <1x1 containers.Map> unsupported class

LaCl3 = saveVarsMat.LaCl3; % <1x1 containers.Map> unsupported class

MgCl2 = saveVarsMat.MgCl2; % <1x1 containers.Map> unsupported class

ZrCl4 = saveVarsMat.ZrCl4; % <1x1 containers.Map> unsupported class

clear saveVarsMat;
